name: Deploy Birdbot

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'staging'
      
jobs:
  deploy:
    uses: kurzgesagt-in-a-nutshell/.github/.github/workflows/deploy-birdbot.yml@main
